# Generated by Django 4.2.10 on 2024-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
