# Generated by Django 4.2.10 on 2024-06-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logomodel',
            old_name='image',
            new_name='logo',
        ),
    ]
