# Generated by Django 4.2.10 on 2024-06-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutusmodel_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='AboutUsModel',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
