# Generated by Django 4.2.10 on 2024-06-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactusmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmodel',
            old_name='title',
            new_name='subject',
        ),
    ]
