# Generated by Django 4.2.10 on 2024-06-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_title_contactusmodel_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmodel',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
