# Generated by Django 4.2.10 on 2024-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
