# Generated by Django 4.2.10 on 2024-06-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(to='shop.productcategorymodel', verbose_name='product_category'),
        ),
    ]
