# Generated by Django 4.2.10 on 2024-06-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_avg_rate'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItemModel',
        ),
    ]
