# Generated by Django 4.2.10 on 2024-06-09 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_rename_price_orderitemmodel_single_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='used_by',
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
