# Generated by Django 4.2.10 on 2024-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shippinStatus',
            field=models.IntegerField(choices=[(1, 'processing'), (2, 'posted'), (3, 'returned')], default=1),
        ),
    ]
