# Generated by Django 4.2.10 on 2024-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.CharField(max_length=255)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('response_json', models.JSONField(default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'success'), (3, 'failed')], default=1)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
